# Generated by Django 4.2.5 on 2023-10-09 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='starts',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
